### ISSUE TITLE
"Multirun" Configuration Is Not Available in PhpStorm

### ISSUE THREAD

**Issue by sshymko** [rkhmelyuk/multirun#1]
After successful installation of the plugin version 0.1 in PhpStorm 6.0.3 (build #PS-129.672) "Multirun" configuration type is not available in the menu.

![phpstorm_settings_plugins_multirun](https://f.cloud.github.com/assets/1231423/668073/bce54678-d805-11e2-84db-bd4efa1c26b7.png)

![phpstorm_run_debug_configuration_add](https://f.cloud.github.com/assets/1231423/668072/bce54934-d805-11e2-89e9-8c52e6c50c04.png)

**Comment by rkhmelyuk** [comment]
Actually, I have the same problem with PyCharm. I had to spend more time to fix that for those IDEs.

**Comment by rkhmelyuk** [comment]
I had to enable the option that allows using plugin in other IDEs. I got it working in PyCharm and think that it should be working in PhpStorm as well.

**Comment by rkhmelyuk** [comment]
Btw, I've uploaded the new version to plugins repository. It should become available soon.

**Comment by rkhmelyuk** [comment]
Re-uploaded the plugin.

**Comment by sshymko** [comment]
Confirmed: plugin version 0.2 is compatible with PhpStorm 129.757.
