### ISSUE TITLE
Need to support Debug as well as Run

### ISSUE THREAD

**Issue by jgindin** [rkhmelyuk/multirun#13]
Ideal: Allow me to Run some of the configurations and Debug others.
- When adding a configuration, allow me to choose if that configuration should be Run or Debug.

OK: Allow me to Debug all the configurations.
- Enable the "Debug" button on the toolbar

**Comment by rkhmelyuk** [comment]
Added debug for the Multirun configuration. 

Ideal solution is too ideal, even though it gives flexibility, it also overcomplicates work with plugin and doesn't match the way IDEA does it.
