### ISSUE TITLE
Fails to run on OS X

### ISSUE THREAD

**Issue by navels** [rkhmelyuk/multirun#15]
OS X 10.8.4
IntelliJ version: 12.0.4 ultimate

I set up a multirun configuration, click "Run" and get the following error:

```
NoClassDefFoundError: Error during dispatching of java.awt.event.MouseEvent[MOUSE_RELEASED,(476,33),absolute(476,55),button=1,modifiers=Button1,clickCount=1] on frame1: com/intellij/execution/runners/ExecutionEnvironmentBuilder
```

Thanks,
Lee

**Comment by rkhmelyuk** [comment]
I'm able to reproduce the issue. `ExecutionEnvironmentBulder` was introduced in recent IDEA version (12.1), that's the reason of this issue. I'm going to releaes the fix early next week

**Comment by navels** [comment]
Great, thanks!

**Comment by rkhmelyuk** [comment]
Uploaded the new version of plugin to the repository.
