### ISSUE TITLE
Serial execution

### ISSUE THREAD

**Issue by pschichtel** [rkhmelyuk/multirun#19]
This is an awesome plugin, however one thing prevents me from using it currently.

My current (maven) project consists of 5 differen repositories and maven projects:
- parent
- core (depends on parent)
- 
  1. aggregator project (depends on core)
  2. aggregator project (dependes on 1. aggregator)
  3. aggregator project (depends on 1. and 2. aggregators)

As you see due to their dependencies, they can not be run in parallel.

Would you mind adding this or could you provide me with information on where this should be implemented in the plugin?

**Comment by rkhmelyuk** [comment]
Hey,

Thanks for using plugin.

I can recommend you to check following 2 links and see if they work for you. Let me  know if what you want is different.
- https://github.com/rkhmelyuk/multirun/wiki#start-each-configuration-one-by-one
- https://github.com/rkhmelyuk/multirun/wiki/How-to-run-configurations-with-Multirun

**Comment by pschichtel** [comment]
I looked at those already. The point is, serial starting is not enough. 2 depending maven projects may not build at the same time, otherwise it becomes inconsistent. Multirun started them all after each other, but they were running in parallel which caused some to fail due to an invalid jar file which was at taht moment being deployed to the local repository by a previous project.

**Comment by rkhmelyuk** [comment]
Is pause between starting configurations is something that could help with your problem?

https://github.com/rkhmelyuk/multirun/issues/21

**Comment by pschichtel** [comment]
Nope, that would be an unreliable workaround

**Comment by rkhmelyuk** [comment]
Starting from version 1.11.1 it is possible to run one configuration just after the other configuration completed when selecting "Start configurations one by one" and using negative delay.

Multirun now does not wait for delay time to start next configuration if previous has completed. In this case, even if using large delay, once current task is completed, the next will start immediately.
