### ISSUE TITLE
Released version 0.9 is compiled against Java 7

### ISSUE THREAD

**Issue by derkork** [rkhmelyuk/multirun#24]
I just updated to the released version 0.9 and it's compiled against Java 7. This does not seem to work with the latest EAP of IDEA 14, as I'm getting "Unsupported Major/Minor Version: 51" errors when the plugin is loaded. Recompiling the Plugin with Java 6 from the sources seems to do the trick.

**Comment by rkhmelyuk** [comment]
I"ll upload compiled with java6 version tomorrow.

Thanks for reporting this,

Ruslan
