### ISSUE TITLE
Multirun v0.9 throws an Exception and it can't be enabled

### ISSUE THREAD

**Issue by jhuesos** [rkhmelyuk/multirun#25]
After updating to multirun version 0.9 this morning, I can no longer enable it. It throws an exception when starting Intellij Idea.

I am attaching a screenshot of the exception (I couldnt select the text, sorry)

![screen shot 2014-09-02 at 10 00 20](https://cloud.githubusercontent.com/assets/339609/4115404/7e312280-3277-11e4-8251-ff6f777c1e23.png)

**Comment by rkhmelyuk** [comment]
Rebuilt with Java 6 and uploaded a new version.

**Comment by rkhmelyuk** [comment]
Thanks for reporting!
