### ISSUE TITLE
Version 0.9 crashes IJ 13.1.4 on OS X

### ISSUE THREAD

**Issue by navels** [rkhmelyuk/multirun#26]
I'm on OS X with Intellij 13.1.4. Just updated the plugin today to 0.9 and get this error:

Plugin 'com.khmelyuk.multirun failed to initialize and will be disabled. Please restart Intellij IDEA.

at which point my UI is frozen and I have to find and kill the intellij process on the command line.

**Comment by rkhmelyuk** [comment]
Version for 13 was build using wrong SDK. Fixed. New version is 0.9.2

Thanks for reporting.
