### ISSUE TITLE
Webstorm 9, Run tab re-use no longer seems to be working

### ISSUE THREAD

**Issue by wedwards99** [rkhmelyuk/multirun#27]
After upgrading to Webstorm 9 the Multirun plugin had to be re-installed.   Since then existing or new Multirun configurations seem to not recognize the setting for "Re-use tab to run configuration" and always start new tabs.

Thanks very much, Will

**Comment by rkhmelyuk** [comment]
Can you check the recent version of this plugin?

**Comment by wedwards99** [comment]
The recent version now works as advertised, thanks.  One problem (for me anyway) is that the definition is now re-use tab, _except tab of failed configurations_, and I do want to re-use the tabs regardless of its failure status.  Things like the stop button in web storm is a non zero exit code and I think this defines it as a failed configuration.

Thanks again, Will
