### ISSUE TITLE
incompatible with intellij 14

### ISSUE THREAD

**Issue by gokhan-berberoglu** [rkhmelyuk/multirun#28]
latest version (0.9.2) is not compatible with intellij 14

workaround: uninstall 0.9.2. install multirun again then intellij14 will pick 0.9.1 which is compatible.

so this is only an issue if you upgrade from 13 to 14, due to strange version numbers.

**Comment by rkhmelyuk** [comment]
Some strange API issue caused this. Updated Multirun with a new version soon (in next few hours). Please, use it and re-open if any issue.
