### ISSUE TITLE
IntelliJ 14: runned configurations are pinned regardless of tab re-use.

### ISSUE THREAD

**Issue by AlbertBrand** [rkhmelyuk/multirun#30]
Previously, only when multirun option 're-use tab to run configuration' was used, the started configuration was pinned. Now, it seems that it is always pinned in IntelliJ 14 / Multirun 0.9.1.

**Comment by rkhmelyuk** [comment]
Tabs would be pinned, unless 're-use tab to run configuration' is set. Going to update Multirun and see it works as expected. Please reopen if you still have the issue.
