### ISSUE TITLE
Fail to install on WebStorm 9.0.1

### ISSUE THREAD

**Issue by ido-ran** [rkhmelyuk/multirun#31]
I've download the jar file multirun-13.jar, when I try to install it in WebStorm 9.0.1 I get an error message:
Plugin Multirun is incompatible with current installation.

Any ideas?

**Comment by wedwards99** [comment]
We had the same problem here, this is the IM session I had with a colleague at the time, I hesitate to say it's _the_ solution but it worked for us, hope it helps:

`...in the plugins page it showed Multirun in red or something with an Uninstall Plugin button at the top.  
Clicked the uninstall button and it upgraded it instead after a restart it all seems to be working ok.
Basically I think an uninstall and install of multirun fixes the problem`

**Comment by ido-ran** [comment]
Thanks for the tip. I'm not able to get it install in the first place.

**Comment by GordonShamvey** [comment]
Hi. Facing same problem with IntellijIDEA after I`ve upgraded it to 14.0.2. 
Any update on this?

**Comment by rkhmelyuk** [comment]
Going to update plugin in a few hours. Should work now. Please, reopen if still would have issue. Thank you!
