### ISSUE TITLE
Plugin does not work with IntelliJ 14.1 EAP

### ISSUE THREAD

**Issue by nickhristov** [rkhmelyuk/multirun#33]
Not sure if IntelliJ changed their SPI or what is the reason. Multirun simply does not load under that revision.

**Comment by rkhmelyuk** [comment]
Thanks for reporting. I will check that in next few days.

**Comment by pjjanak** [comment]
Any word on this?

**Comment by rkhmelyuk** [comment]
Going to spend some time to fix pending issues with multirun for new
versions of IDE.

**Comment by ghost** [comment]
I have multirun available in latest EAP but it fails on every configuration after executing all "Before" tasks...

**Comment by ghost** [comment]
@rkhmelyuk thanks for this plugin man, its very usefull in some cases :) 
i think i'll help you with this, i've noticed several bugs (concurrent/non concurrent execution of configs) + i have one feature request...

**Comment by rkhmelyuk** [comment]
vach@ - thanks, just post the bugs you have or send pull requests; I'm going to spend some time fixing things next couple weeks.

**Comment by kenfox** [comment]
14.1 is released for general use now. Losing multirun for a while sure reminds me why I installed it in the first place! ;)

**Comment by nickhristov** [comment]
It appears to be a purely plugin.xml version limit. I can send a pull request; however, my testing has been limited to about a day of usage.

**Comment by rkhmelyuk** [comment]
Thanks Nick. Going to look today too, as its time to update to new Idea!

**Comment by rkhmelyuk** [comment]
Thanks everyone. Sorry for such late action on this. New version should be available in a few hours.
