### ISSUE TITLE
Does not work in Intellij 15 EAP

### ISSUE THREAD

**Issue by pjjanak** [rkhmelyuk/multirun#34]
Like the title says. Getting the following error when attempting to run a multi-run configuration:

`NoSuchMethodError: com.intellij.execution.runners.ExecutionEnvironment.(Lcom/intellij/execution/configurations/RunProfile;Lcom/intellij/execution/Executor;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/openapi/project/Project;Lcom/intellij/execution/configurations/RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/execution/RunnerAndConfigurationSettings;Ljava/lang/String;)V`

**Comment by Donnerbart** [comment]
Same exception here with 15 EAP.

**Comment by amorfis** [comment]
Same here. Build 142.5047.6

**Comment by rkhmelyuk** [comment]
Going to look at it in next few days. Got the same problem :)

**Comment by rkhmelyuk** [comment]
Version 1.1 is available now in the repository. It supports IntellijIDEA 15 version.
