### ISSUE TITLE
multidebug? Run as debug option?

### ISSUE THREAD

**Issue by cescoferraro** [rkhmelyuk/multirun#36]
Is there such feature? Is there any chance of happening?

**Comment by rkhmelyuk** [comment]
It's currently unsupported. Yes, it's possible to add this. I'll try to get look to it this weekend.

Are you ok with it being supported only for idea 15?

**Comment by cescoferraro** [comment]
Yeah I am OK! I got it installed through the EAP, but am not currently using it because its still buggy on Ubuntu 15( Top bar menus refusing to open after clicking it a few times. WIll file an issue on youtrack).

**Comment by rkhmelyuk** [comment]
v1.0.2 for Idea14 should enable debugging.
v1.1.2 for Idea15 EA should enable debugging.

Let me know if any issues.

**Comment by cescoferraro** [comment]
I dont see any changes.How do I choose the debug mode? Had to install the plugin from disk. Downloading from the GUI give me errors. Neither was able to update it from the GUI. Idea 14 btw, version 1.0.2
