### ISSUE TITLE
Run with Coverage

### ISSUE THREAD

**Issue by Donnerbart** [rkhmelyuk/multirun#37]
Hi,

I would like to use Multirun to start coverage tests for a large multi-module project with several hours of test runtime, so I can go away and leave it unattended. At the moment I have to start the tests for each module manually after each other.

Multirun would be a very good match, but I cannot start it with Coverage, just `Run` and `Debug` are available. Any chance to get this implemented?

**Comment by rkhmelyuk** [comment]
I need to check how to implement this. Don't think that would be much difference from Run/Debug runner action.
