### ISSUE TITLE
Start configurations one by one and forked process?

### ISSUE THREAD

**Issue by Darkvater** [rkhmelyuk/multirun#39]
Love the idea of this plugin. I have tried using it together with cucumber-jvm, but it seems that after the cucumber process starts it forks off the actual runner, thus multirunner thinking it is ready to start the next test in sequence even if "Start configurations one by one" is set.

Is there any way of forcing the plugin to wait for the finish of the currently running configuration?

**Comment by rkhmelyuk** [comment]
You can use "Start configurations one by one" and use some delay (just to the right side of this option). However, this means that it will wait same delay for each started configuration.

**Comment by Darkvater** [comment]
That is fine as long as you know how long a certain run-configuration takes. Thanks, I'll try playing with that.
