### ISSUE TITLE
Stopped working after WebStorm upgrade from 11 to 2016.1

### ISSUE THREAD

**Issue by slanska** [rkhmelyuk/multirun#40]
I have been enjoying your plugin for few months and after upgrade to WebStorm 2016.1 it stopped working. 
Would it be possible to fix plugin? Native Compound project does not seem to support debugging (allows only to run bundle of projects). Appreciate it!

**Comment by mmmod** [comment]
Exactly the same problem with IntelliJ IDEA 2016.1. Multirun got downgraded from 1.1.2 to 0.8 when IntelliJ started, probably because the 1.1.2 is not marked as compatible with the new version (but 0.8 is).

**Comment by navels** [comment]
I've increased the version compatibility, rebuilt, and tested against Intellij 15, 2016.1, and Webstorm 2016.1.  (New plugin version is 1.1.3.)

@rkhmelyuk, let me know if you'd like me to submit a PR.  I'd also be willing to take over updating the plugin if you no longer have the time or interest.  Thanks.

[multirun.jar.zip](https://github.com/rkhmelyuk/multirun/files/179887/multirun.jar.zip)

**Comment by rkhmelyuk** [comment]
Hi @navels,

That is awesome if you have a fix. Can you pls submit PR to add the change into the repository.

I'd be happy if you could take over maintaining this plugin. Send me your plugins.jetbrains.com username, and I'll be able to add you to the developers list.

Thanks,
Ruslan

**Comment by navels** [comment]
Sounds good. My username at jetbrains is also navels.  PR to come . . .

**Comment by rkhmelyuk** [comment]
@navels - I've added you as a collaborator to this repository.

**Comment by observstream** [comment]
Any update on releasing a new version?

**Comment by navels** [comment]
Released 1.1.3.
