### ISSUE TITLE
Execute next configuration after the previous configuration has finished successfully

### ISSUE THREAD

**Issue by Phitherek** [rkhmelyuk/multirun#44]
I want to use this plugin for setting up deployment, and then stopping and starting the server. I would like to be able to create a queue of configurations, which is not really what the "Run configurations one by one" does right now. As the time of performing task varies, the pause in seconds is not really helpful in this case.
Also, configuration that fails should abort running the next ones in the queue in this case.

**Comment by luisesp19** [comment]
Maybe you can use the "Before launch" feature and add "Run Another Configuration" as many times as you need

**Comment by ratulmukh** [comment]
Doing this worked pretty well. However, for the configurations in the 'before launch', their tabs close as soon as execution is over. :(. Gives me very little time to see the logs and can be limiting.

**Comment by navakrishna** [comment]
Before Launch is not applicable for our use case, we have maven launchers and want to execute independently when it run in group launch, dependency is required and want to use start each configuration one by one avoiding with delay option. Is there any possibility?

**Comment by rkhmelyuk** [comment]
Sounds to be similar to https://github.com/rkhmelyuk/multirun/issues/19.

**Comment by rkhmelyuk** [comment]
Starting from version 1.11.1 it is possible to run one configuration just after the other configuration completed when selecting "Start configurations one by one" and using negative delay.

Multirun now does not wait for delay time to start next configuration if previous has completed. In this case, even if using large delay, once current task is completed, the next will start immediately.
