### ISSUE TITLE
Replace running tabs when stop and start again

### ISSUE THREAD

**Issue by alexluix** [rkhmelyuk/multirun#47]
Hello

Thank you for a great plugin! This is the only third-party plugin I use in IDEA.

The only suggestion I have for even better usability is to have an option to replace/override/reuse the existing inactive tabs. So when I say stop-all and then start-all again – I expect running tabs to be reused and no inactive/stopped tabs should be left. Currently new tabs created.

Currently when I need to restart processes I have to stop them first and then manually close-all running tabs and then start-all.

Alternatively or separately I would suggest to add restart-all functionality – I think it will be in high use.

Thank you very much.

**Comment by jzuken** [comment]
I second that! Truly awesome plugin, thanks a lot for it! But those endlessly emerging tabs are a nightmare.

**Comment by thhart** [comment]
Yes, this is a must, any chance for it?

**Comment by thhart** [comment]
Maybe you can give a hint where to look into, what is the point in the code where the tabs get opened, perhaps it is possible to support and provide a patch?!

**Comment by jenkeeri** [comment]
I would also enjoy this functionality! I do see a checkbox in the config about reusing tabs, but that does not make a difference...

**Comment by rkhmelyuk** [comment]
Plugin pins every tab it starts. When process is being killed (either by killing all or just single process), the pin on tab is not cleared properly. This sounds like a bug.

**Comment by rkhmelyuk** [comment]
That was a tricky bug, but should be resolved now.
