### ISSUE TITLE
Stopped working after Intellij IDEA upgrade from 16.2 to 16.3

### ISSUE THREAD

**Issue by JiahaoLi** [rkhmelyuk/multirun#49]
Multi run is very convenient tool. However it is no longer working in new version of Intellij 2016.3.

**Comment by kdmandawe** [comment]
Any plan for 2016.3 support? Unfortunately the built-in 'compound' plugin lacks the tools available in multirun like 'start configurations one by one' and with delay of 'n' seconds.. I need those.

**Comment by mfedko** [comment]
For now you can build it with gradle and install from local directory.

**Comment by navels** [comment]
I've compiled and published an update which is compatible with 2016.3.

**Comment by rkhmelyuk** [comment]
Thank you @navels for fixing plugin!

**Comment by kdmandawe** [comment]
Goodbye 2016.2! I can confirm multirun now works with 2016.3!
