### ISSUE TITLE
Run/Debug stops working for no reason

### ISSUE THREAD

**Issue by eyalrin** [rkhmelyuk/multirun#50]
Sometimes, for no apparent reason, the run and debug option for my run configurations stops working. I press the button, but nothing happens. I need to restart IntelliJ to fix it.

This happens in versions 14.1.5, 15.0.6 and 2016.3.1 (using currently)
OS X 10.12.2

Attached is the log file.
[idea.txt](https://github.com/rkhmelyuk/multirun/files/695583/idea.txt)

**Comment by navels** [comment]
This looks like more of an IJ issue.  Can you raise an issue on their tracker?

**Comment by navels** [comment]
LOL I see you already did that and they told you to come here :)

I've commented on your IJ issue, we'll see if they can help.

**Comment by eyalrin** [comment]
OK, thank!

BTW - this happened to me on a Windows pc as well in the past (same project).

**Comment by rkhmelyuk** [comment]
Check with new version 1.11.1. And let us know if you still see that issue.
