### ISSUE TITLE
Multirun gives error in IntelliJ IDEA 2017.3 EAP, build: #IU-173.3302.5

### ISSUE THREAD

**Issue by tommy-andersen** [rkhmelyuk/multirun#59]
When attempting to use the multirun feature in IDEA 2017.3 EAP (build IU-173.3302.5) I get the following error:

    Error running 'Some MRun Project': com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/configurations/RunProfile;Lcom/intellij/execution/Executor;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/openapi/project/Project;Lcom/intellij/execution/configurations/RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/execution/RunnerAndConfigurationSettings;Ljava/lang/String;)V

I have tried multiple different Multirun builds, the same result occurs with them all.

**Comment by navels** [comment]
Plugin updated for 2017.3, can you let me know if this fixes your issue?

**Comment by tommy-andersen** [comment]
The new update works. Thank you.
