### ISSUE TITLE
Error while executing a multirun configuration

### ISSUE THREAD

**Issue by lennartblom** [rkhmelyuk/multirun#60]
I just found out about the multirun plugin in PyCharm today I wanted to start my distributed API with it. Unfortunately I get an error instantly if I hit the "run" button.

**My setup is the following:**
Jetbrains PyCharm 2017.3 EAP 
Mac OS X High Sierra

**The error message looks like this:**
`Error running 'My API': com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/configurations/RunProfile;Lcom/intellij/execution/Executor;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/openapi/project/Project;Lcom/intellij/execution/configurations/RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/execution/RunnerAndConfigurationSettings;Ljava/lang/String;)V` 

The plugin feature looks very handy, so I really look forward to getting started with "MultiRun"! :)

Kind regards from Germany, Osnabrück!
Lennart Blom

**Comment by navels** [comment]
Plugin updated for 2017.3, can you let me know if this fixes your issue?

**Comment by lennartblom** [comment]
Mh... I got version 0.8 running. But there is no evidence for a new update. Did I miss something? Or do you mean the 0.8 version?

**Comment by navels** [comment]
Yes, 0.8 is the new version.

**Comment by lennartblom** [comment]
Mh... With "I got version 0.8 running" I did mean, that I have installed the 0.8 version. But the described error occurs, as I explained. So I did not find any update with a newer version to fix my issue...

Sorry for my indistinct wording.

**Comment by navels** [comment]
Got it, thanks for the clarification.  If you can provide some steps for reproducing the problem (or a github project) I'll look into it.

**Comment by lennartblom** [comment]
Unfortunately it is pretty simple to explain.

If I do not add any configuration to run with the "multi run configuration" I get no errors but a prompt, that I should add at least one:
![screen shot 2017-11-02 at 15 30 17](https://user-images.githubusercontent.com/4670057/32331430-29fbcc86-bfe3-11e7-867c-609f897e211b.jpg)

If I added one configuration I get the error message above:
![screen shot 2017-11-02 at 15 30 39](https://user-images.githubusercontent.com/4670057/32331473-4afaba96-bfe3-11e7-9f0b-35fc91125b7f.jpg)

Anything I am doing wrong?

**Comment by Mavrick64** [comment]
Any new on the issue? I got the same problem with IntelliJ 2018.1. Multirun is also version 0.8. 
Could you let us know when we can expect a fix? 
Thanks

**Comment by j-walker23** [comment]
This is also happening on Pycharm 2018.1. The same project/Multirun config was working with latest PyCharm 2017.x.

**Comment by leosegretain** [comment]
Same error on linux after updating IntelliJ + multirun (0.8)

**Comment by navels** [comment]
I should have some time to take a look this weekend.

**Comment by navels** [comment]
1.9 released, please let me know if this fixes your issue.

**Comment by Mavrick64** [comment]
That's great! It works perfectly for me (intelliJ 2018.1 / Ubuntu 16.04)! Thanks a lot for the quick update!
