### ISSUE TITLE
multirun 1.8 is not compatible with IntalliJ 2018.1 

### ISSUE THREAD

**Issue by koretzki** [rkhmelyuk/multirun#61]
> Error running 'AllApps': com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/configurations/RunProfile;Lcom/intellij/execution/Executor;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/openapi/project/Project;Lcom/intellij/execution/configurations/RunnerSettings;Lcom/intellij/execution/configurations/ConfigurationPerRunnerSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/execution/RunnerAndConfigurationSettings;Ljava/lang/String;)V

shows when trying to execute existing or new MultiRun configuration.

**Comment by OOPMan** [comment]
I'm not sure the author will update, see the opening page of the repo, he recommends you use the compound configs now included in IntelliJ

**Comment by koretzki** [comment]
for whom is keeping update the plugin, something similar happened a few months ago on issue #60

**Comment by navels** [comment]
I'll get to it today

**Comment by navels** [comment]
1.9 released, please let me know if this fixes your issue.

**Comment by cazacugmihai** [comment]
Multirun `1.9` works for me in IntelliJ IDEA `2018.1`. 

Thank you for this quick fix!

**Comment by koretzki** [comment]
thanks @navels , working great.
