### ISSUE TITLE
Multi Run Configuration across multiple Spring Boot projects

### ISSUE THREAD

**Issue by lennartblom** [rkhmelyuk/multirun#62]
Is it possible to use a multi run configuration across multiple projects? I currently do not see any possibility to use the configuration with two projects. 

I would be delighted if I am able to start other services (other intelliJ projects) from my project, which I am currently working on.  Even more awesome would be other frameworks as well (e.g. python / node.js)

Because having more than one project windows open, can pretty much slow down the dev machine.

Thanks for your awesome work so far! And thanks in advance for your help!

Cheers from Germany,
Lennart Blom

**Comment by rkhmelyuk** [comment]
Unfortunately, it doesn't seem to be supported by IntellijIDEA, so can't be added as part of plugin.

**Comment by lennartblom** [comment]
Ok. Thanks @rkhmelyuk for getting back to me! 🙂
