### ISSUE TITLE
Doesn't appear to be any way to sequentially run configs?

### ISSUE THREAD

**Issue by ultrapingu** [rkhmelyuk/multirun#63]
Am I right in thinking that there isn't any way to have the next config wait for the previous config to finish before it runs?

**Comment by serragnoli** [comment]
I'm curious about it as well. It seems there is no way.

**Comment by rkhmelyuk** [comment]
There is a "Start configurations one by one". Just checked and it seems to have a bug: **I have to uncheck this option** to get the desired behavior. Not sure what causing this bug, but I suggest you to play with that checkbox. 

During my experiment, I've unchecked all other checkboxes, but you can play with them as well.

**Comment by rkhmelyuk** [comment]
This one should be working starting version 1.11. Just check "Start configurations one by one" and use *negative* delay. Multirun in this case will run each configuration one by one sequentially.
