### ISSUE TITLE
I can't start two processes at the same 

### ISSUE THREAD

**Issue by matteocollina** [rkhmelyuk/multirun#65]
**Environment**
IntelliJ IDEA 2018.1.1 (Ultimate Edition)
Build #IU-181.4445.78, built on April 9, 2018
For educational use only.
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

I would like to start the two processes at the same time but it does not work.

1. I unchecked "Start configuration one by one"
2. I checked "I re-use tab to run configuration"
3. I put two processes in "Choose configuration to run" but if i print the timestamp, the second process starts 2 seconds later.

Is there a way to get them started in parallel?
Thank you.

**Comment by rkhmelyuk** [comment]
I do not think it will be possible to make them to start at the same instant. With unchecked "Start configuration one by one", plugin triggers configurations start almost immediately, however, IntelliJ will do certain work to start configurations, which would result in lags between configurations.
