### ISSUE TITLE
Mssing "green dot" when a configuration is started with multirun

### ISSUE THREAD

**Issue by HugoSart** [rkhmelyuk/multirun#66]
When you drop down the configuration list, usually there is a green dot on those configurations which are already running. If those configurations were started with multirun, the green dot does not appears.

MULTIRUN VERSION: v1.9
IDE VERSION: IntelliJ Ultimate 2018.3.2
OS: Deepin 15.9

**Comment by rkhmelyuk** [comment]
I can't reproduce the issue. I'm going to resolve this issue, as it's 2 years old. Feel free to re-open if you still have this issue.
