### ISSUE TITLE
Incompatibilities of Multirun 1.9 plugin with recent IDE builds 

### ISSUE THREAD

**Issue by serejke** [rkhmelyuk/multirun#67]
Hello,
we've detected a couple of incompatibilities of the plugin Multirun with newest IDE builds, caused by recently removed and deprecated class `com.intellij.internal.statistic.UsageTrigger`.

You may see verification results on https://plugins.jetbrains.com/plugin/7248-multirun/update/44620.

"until" build has been restricted for your plugin to 191.4000, the latest version compatible with the plugin.

Please update the plugin in the repository.

Thanks!

**Comment by navels** [comment]
plugin has been updated
