### ISSUE TITLE
Problems since Version 2019.1 of IntelliJ

### ISSUE THREAD

**Issue by sbicher** [rkhmelyuk/multirun#68]
Since the installation of 2019.1 I get the error message 

Error running '<JOB_NAME_HERE>': com/intellij/internal/statistic/UsageTrigger

and the runners don't start.
A colleague of mine has the same problem

**Comment by pakro** [comment]
Also affected by this issue. Having several spring boot applications that I want to start with this plugin but it does not work anymore.

**Comment by navels** [comment]
plugin has been updated

**Comment by sbicher** [comment]
Thanks, works excellent again!
Great work and really fast.
