### ISSUE TITLE
Consider writing a dashboard?

### ISSUE THREAD

**Issue by onlyeat3** [rkhmelyuk/multirun#71]
Idea Ultimate have spring boot dashboard, very useful. But can't be used for non-Spring boot projects, consider writing a similar version?

**Comment by rkhmelyuk** [comment]
Luckily Run Dashboard is a feature provided by IDE. You just need to add Multirun to that list.

See how to do that below:
* https://yoni-1117.tistory.com/188
* https://blog.jetbrains.com/idea/2019/08/services-tool-window-one-place-to-rule-them-all/
