### ISSUE TITLE
Can't start with debug mode in version 2019.2

### ISSUE THREAD

**Issue by dualbootsoftware** [rkhmelyuk/multirun#72]
Hi, I upgraded to Webstorm version 2019.2 and can't start any multi-run configurations in 'Debug' mode. It works properly if you start it in Run mode, but in Debug mode it complains like this about each step in the multi-run

Error: Debug: there are no runners for Node.js: index.js 

Thanks!

**Comment by michaelcordero** [comment]
Same for IntelliJ 2019.1.3

**Comment by raghuadapa** [comment]
Same issue. I upgraded to 2019.2 and debug mode stopped working. Run is working fine. any help is truly appreciated. 

Below is the screen print of the error message.

**"Error: Debug: there are no runners for Application: Replay"**

![image](https://user-images.githubusercontent.com/30295827/62073282-64af3100-b20e-11e9-97fb-872da3b2a1dd.png)

**Comment by stmaute** [comment]
Can confirm this issue. Any news if and when it will be fixed?

**Comment by pull-vert** [comment]
my multirun (v1.10) Configuration using debug mode was not working with IntelliJ 2019.2 but now with the latest IntelliJ 2019.2.1 it works perfectly !

**Comment by dualbootsoftware** [comment]
Same here, it is fixed when using 2019.2.1. Closing.
