### ISSUE TITLE
Delay < 1s

### ISSUE THREAD

**Issue by BenjD90** [rkhmelyuk/multirun#75]
Hello,

Just asking, but that would be nice to be able to set the delay with a value in milliseconds.
My use case is that I start 15 apis, and I prefer to keep the order at launch. With delay == 0, the order is not guaranteed, I'd like to set a delay at 0.1 or 0.5s seconds, but I can't :'(

Thanks for this plugin :)

**Comment by rkhmelyuk** [comment]
Multirun now supports sub-second delay starting from version 1.11. Minimal fraction is 100ms.
