### ISSUE TITLE
Deprecated ConfigurationFactory.getId needs to be overridden

### ISSUE THREAD

**Issue by clausavram** [rkhmelyuk/multirun#76]
Hello,
I stumbled upon this warning in the `/var/log/syslog`, though it didn't cause any visible issues:
```
util.DeprecatedMethodException - The default implementation of method 'com.intellij.execution.configurations.ConfigurationFactory.getId' is deprecated, you need to override it in 'class com.khmelyuk.multirun.MultirunConfigurationType$1'. The default implementation delegates to 'getName' which may be localized but return value of this method must not depend on current localization.
```

- <details>
    <summary>Full log with stack trace:</summary>

    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: 2020-12-02 13:47:20,284 [   5467]   WARN - util.DeprecatedMethodException - The default implementation of method 'com.intellij.execution.configurations.ConfigurationFactory.getId' is deprecated, you need to override it in 'class com.khmelyuk.multirun.MultirunConfigurationType$1'. The default implementation delegates to 'getName' which may be localized but return value of this method must not depend on current localization.
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: com.intellij.util.DeprecatedMethodException: The default implementation of method 'com.intellij.execution.configurations.ConfigurationFactory.getId' is deprecated, you need to override it in 'class com.khmelyuk.multirun.MultirunConfigurationType$1'. The default implementation delegates to 'getName' which may be localized but return value of this method must not depend on current localization.
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.util.DeprecatedMethodException.reportDefaultImplementation(DeprecatedMethodException.java:40)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.configurations.ConfigurationFactory.getId(ConfigurationFactory.java:82)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunManagerImpl.getFactory(RunManagerImpl.kt:1009)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunManagerImpl.getFactory(RunManagerImpl.kt:1002)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:208)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:60)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:43)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:21)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:65)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:175)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:216)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunManagerImpl.loadSharedRunConfigurations(RunManagerImpl.kt:838)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:814)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:72)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:445)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:377)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:124)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:49)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:402)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:53)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:13)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:43)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:42)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:457)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:440)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.execution.impl.ProjectRunConfigurationInitializer.serviceCreated(ProjectRunConfigurationInitializer.kt:28)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectExImpl$init$$inlined$runOnlyCorePluginExtensions$1.accept(projectLoader.kt:87)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectExImpl$init$$inlined$runOnlyCorePluginExtensions$1.accept(projectLoader.kt)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:296)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectExImpl.init(ProjectExImpl.kt:286)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:173)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:240)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:51)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectManagerExImpl$openProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(ProjectManagerExImpl.kt:103)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectManagerExImpl$openProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(ProjectManagerExImpl.kt:51)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressTask$1.run(ProjectFrameAllocator.kt:86)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at java.base/java.security.AccessController.doPrivileged(Native Method)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    Dec  2 13:47:20 dev-machine jetbrains-idea-ce.desktop[8207]: #011at java.base/java.lang.Thread.run(Thread.java:834)

</details>

- <details>
        <summary>IntelliJ version: IDEA 2020.3 - Build #IC-203.5981.155</summary>

      IntelliJ IDEA 2020.3 (Community Edition)
      Build #IC-203.5981.155, built on December 1, 2020
      Runtime version: 11.0.9+11-b1145.21 amd64
      VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
      Linux 4.15.0-126-generic
      GC: ParNew, ConcurrentMarkSweep
      Memory: 6966M
      Cores: 4
      Registry: debugger.watches.in.variables=false
      Non-Bundled Plugins: com.khmelyuk.multirun, com.thvardhan.gradianto, org.nik.presentation-assistant, Docker, Error-prone plugin, FitNesse
      Current Desktop: GNOME

    </details>

- Multirun plug-in version: 1.11.2
  ![image](https://user-images.githubusercontent.com/4466789/100869617-f5062180-34a5-11eb-98ca-99634d6d2471.png)

**Comment by rkhmelyuk** [comment]
This has been resolved at 1.12. Thanks for reporting.
