### ISSUE TITLE
"with delay" is not work for me

### ISSUE THREAD

**Issue by 10v3** [rkhmelyuk/multirun#81]
I added configuration A and configuration B, and checked "Start configurations one by one", set "with delay" to 10000.0s, but configuration B still runs immediately after configuration A runs.

**Comment by rkhmelyuk** [comment]
Have you tried the value lower than 10000.0s? What is the reason for you to use 10000.0s value for delay?

**Comment by 10v3** [comment]
I tried, 10000s is just an exaggeration, I mean 10s or 100s or 1000s or 10000s are the same.
My English is not good, these are translated by Google Translate, I hope you can understand.

**Comment by rkhmelyuk** [comment]
Sure, I can understand you well.

Just to double confirm, do you have the "Start configurations one by one" checkbox checked? It must be checked for delay to be used.

**Comment by 10v3** [comment]
I’m sure I checked it before, because I tried it many times, so I was very impressed. I tried it again a few minutes ago, the delay is worked now, I don't know why but it's okay, I'm sorry for wasting your time

**Comment by rkhmelyuk** [comment]
No worries, happy to hear it worked this time. Going to resolve. Feel free to re-open if issue happens again.
